language: node_js
branches:
  only:
    - test_travis
after_success:
  - bash scripts/deploy.sh
deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  edge: true
  on:
    branch: test_travis