language: node_js
nodejs:
- stable
branches:
  only:
  - master
env:
  global:
  - REMOTE_PATH=Uploads/Travis_CI/pruebasTravis
  - REMOTE_USER=deploy
  - REMOTE_HOST=167.172.168.233
before_install:
- openssl aes-256-cbc -K $encrypted_76760c530019_key -iv $encrypted_76760c530019_iv
  -in travis.enc -out ../clavesTravis/travis -d
- bash scripts/install.sh
after_success:
- bash scripts/deploy.sh
