language: node_js
nodejs:
- stable
branches:
  only:
  - master
env:
  global:
  - REMOTE_PATH=Uploads/Travis_CI/pruebasTravis
  - REMOTE_USER=deploy
  - REMOTE_HOST=167.172.168.233
before_install:
  - bash ./scripts/install.sh
after_success:
  - bash ./scripts/deploy.sh
